const permissionsConstants = {
  ADD_EMPLOYEE: "addEmployee",
  UPDATE_EMPLOYEE: "updateEmployee",
  DELETE_EMPLOYEE: "deleteEmployee",
  VIEW_EMPLOYEE: "viewEmployee",
  ADD_BRANCH: "addBranch",
  UPDATE_BRANCH: "updateBranch",
  DELETE_BRANCH: "deleteBranch",
  VIEW_BRANCH: "viewBranch",
  GIVE_PERMISSIONS: "givePermissions",
  REMOVE_PERMISSIONS: "removePermissions",
  VIEW_PERMISSIONS: "viewPermissions",
  ADD_ROLES: "addRoles",
  UPDATE_ROLES: "updateRoles",
  DELETE_ROLES: "deleteRoles",
  VIEW_ROLES: "viewRoles",
  VIEW_COMPANY: "viewCompany",
  UPDATE_COMPANY: "updateCompany",
  DELETE_COMPANY: "deleteCompany",
  UPDATE_PROFILE: "updateProfile",
  ADD_STOCK: "addStock",
  VIEW_STOCK: "viewStock",
  UPDATE_STOCK: "updateStock",
  DELETE_STOCK: "deleteStock",
  ADD_SUPPLIER: "addSupplier",
  VIEW_SUPPLIER: "viewSupplier",
  UPDATE_SUPPLIER: "updateSupplier",
  DELETE_SUPPLIER: "deleteSupplier"
}

export default permissionsConstants